language: c
compiler:
    - clang
    - gcc

os:
    - linux
    - osx

addons:
  apt:
    packages:
    - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmocka; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install_cmocka.sh; fi

script: make test
